"""
Django settings for CRUD project.

Generated by 'django-admin startproject' using Django 3.2.23.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8e981-z1=8s#4+_ha@@%ke&p=wj81uf&xm65u&7ewq*c1v#3sz'

# ----------------------------------------------------------
# AUTO DETECT LOCAL / VERCEL ENVIRONMENT
# ----------------------------------------------------------
# Vercel adds an environment variable "VERCEL" = "1"
DEBUG = os.getenv("VERCEL") != "1"

# If running locally → DEBUG=True, ALLOWED_HOSTS=['*']
# If running on Vercel → DEBUG=False, ALLOWED_HOSTS=['.vercel.app']
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['.vercel.app']
# ----------------------------------------------------------


INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',   # Important for static files
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crudoperations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <-- Whitenoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CRUD.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')],  # Your templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CRUD.wsgi.application'


# ------------------ DATABASE -------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ------------------ PASSWORD VALIDATION ---------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# ------------------ INTERNATIONALIZATION ---------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# ------------------ STATIC FILES (For Vercel + Local) ---------------------
STATIC_URL = '/static/'

# Static files where your CSS, JS, images are inside *project/static*
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Production static root (Vercel will use this)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise storage (required on Vercel)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ------------------ DEFAULT PRIMARY KEY --------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
